imports:
    - { resource: easyadmin/ }

easy_admin:
    user:
        name_property_path: 'fullName'
    design:
        menu:
            - label: 'Gestion des vins'
            - entity: 'Product'
              label: 'Vins'
              icon: 'wine-bottle'
            - entity: 'TypeProduct'
              label: 'Catégorie des vins'
              icon: 'tag'
            - entity: 'VineProfile'
              label: 'Profils'
              icon: 'wine-glass'
            - label: 'Gestion logistique'
            - entity: 'Promotion'
              label: 'Promotions'
              icon: 'percent'
            - entity: 'Stock'
              label: 'Stock'
              icon: 'pallet'
        assets:
    site_name: 'Mon Premier Sommelier'
    formats:
        number: '%0.2f'
        datetime: 'd/m/Y H:i'
