imports:
    - { resource: easyadmin/ }

easy_admin:
    list:
        batch_actions: ['delete']
        actions:
            - name: 'new'
              icon: 'plus-circle'
              label: false
            - name: 'edit'
              icon: 'edit'
              label: false
            - name: 'delete'
              icon: 'trash'
              label: false
    user:
        name_property_path: 'fullName'
    design:
        assets:
            css:
                - 'bundles/easyadmin/bootstrap-all.css'
            js:
                - 'bundles/easyadmin/bootstrap-all.js'
        menu:
            - label: 'Gestion des vins'
            - entity: 'Product'
              label: 'Vins'
              icon: 'wine-bottle'
            - entity: 'TypeProduct'
              label: 'Catégorie des vins'
              icon: 'tag'
            - entity: 'VineProfile'
              label: 'Profils'
              icon: 'wine-glass'
            - label: 'Gestion logistique'
            - entity: 'Order'
              label: 'Commandes'
              icon: 'shopping-cart'
            - entity: 'Promotion'
              label: 'Promotions'
              icon: 'percent'
            - entity: 'Stock'
              label: 'Stock'
              icon: 'pallet'
            - entity: 'DeliveryPoint'
              label: 'Points de livraison'
              icon: 'truck'
            - entity: 'DeliveryType'
              label: 'Type de livraisons'
              icon: 'euro-sign'
        form_theme:
            - 'bundles/EasyAdminBundle/layout.html.twig'
    site_name: 'Mon Premier Sommelier'
    formats:
        number: '%0.2f'
        datetime: 'd/m/Y H:i'
