imports:
    - { resource: easyadmin/ }

easy_admin:
    user:
        name_property_path: 'fullName'
    design:
        menu:
            - label: 'Gestion des vins'
            - entity: 'Product'
              label: 'Vins'
              icon: 'wine-bottle'
            - entity: 'TypeProduct'
              label: 'Catégorie des vins'
              icon: 'tag'
            - entity: 'VineProfile'
              label: 'Profils'
              icon: 'wine-glass'
    site_name: 'Mon Premier Sommelier'
