imports:
    - { resource: easyadmin/ }

easy_admin:
    user:
        name_property_path: 'fullName'
    design:
        menu:
            - label : 'Gestion des vins'
            - entity: 'VineProfile'
              label: 'Profils'
    site_name: 'Mon Premier Sommelier'
