imports:
    - { resource: easyadmin/ }

easy_admin:
    list:
        batch_actions: ['delete']
        actions:
            - name: 'new'
              icon: 'plus-circle'
              label: false
            - name: 'edit'
              icon: 'edit'
              label: false
            - name: 'delete'
              icon: 'trash'
              label: false
    user:
        name_property_path: 'fullName'
    design:
        assets:
        menu:
            - label: 'Configuration'
            - label: 'Breadcrumb'
              entity: 'Breadcrumb'
              icon: 'cog fa-spin'
            - label: "Page d'accueil"
              icon: 'home'
              children:
                    - label: 'Image accueil'
                      entity: 'GlobalConfiguration'
                    - label: 'Slider Accueil'
                      entity: 'SliderHome'
            - label: 'Slider MPMD'
              entity: 'SliderMPMD'
            - label: 'Gestion des vins'
            - entity: 'WineDomain'
              label: 'Domaines'
              default: true
            - entity: 'Product'
              label: 'Vins'
              icon: 'wine-bottle'
            - entity: 'TypeProduct'
              label: 'Catégorie des vins'
              icon: 'tag'
            - entity: 'VineProfile'
              label: 'Profils'
              icon: 'wine-glass'
            - entity: 'BoxWine'
              label: 'Box du moment'
              icon: 'boxes'
            - label: 'Gestion Commandes'
            - entity: 'Order'
              label: 'Commandes'
              icon: 'shopping-cart'
            - entity: 'Delivery'
              label: 'Livraisons'
              icon: 'truck-pickup'
            - entity: 'Customer'
              label: 'Acheteurs'
              icon: 'user'
            - entity: 'Promotion'
              label: 'Promotions'
              icon: 'percent'
            - label: 'Gestion logistique'
            - entity: 'Stock'
              label: 'Stock'
              icon: 'pallet'
#            - entity: 'DeliveryType'
#              label: 'Type de livraisons'
#              icon: 'euro-sign'
            - entity: 'NicheOfDelivery'
              label: 'Créneaux de livraison'
              icon: 'clock'
            - label: 'Communautaire'
            - entity: 'TastuceTheme'
              label: 'Thèmes tastuce'
              icon: 'tag'
            - entity: 'Opinion'
              label: 'Modération des avis'
              icon: 'comments'
            - entity: 'Contact'
              label: 'Gestion des contacts'
              icon: 'envelope'
            - entity: 'Newsletter'
              label: 'Inscription newsletter'
              icon: 'newspaper'
        form_theme:
            - 'bundles/EasyAdminBundle/layout.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    site_name: 'Mon Premier Sommelier'
    formats:
        number: '%0.2f'
        datetime: 'd/m/Y H:i'
