security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        user_provider:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Domain\Account\Login\LoginAuthenticator
            logout:
                target: /se-connecter
                path: /se-deconnecter

    access_control:
         - { path: ^/administration-vins, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
