twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/public/build/images': images
    globals:
        stripe_public_key: '%env(resolve:API_PUBLIC_STRIPE)%'
        ga_tag: '%env(resolve:GTAG)%'
        payment_possible: '%env(resolve:PAYMENT_OK)%'
