vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            uri_prefix: /upload/images/products
            upload_destination: '%kernel.project_dir%/public/upload/images/products'
