vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            uri_prefix: /upload/images/products
            upload_destination: '%kernel.project_dir%/public/upload/images/products'
        domain_images:
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            uri_prefix: /upload/images/domain
            upload_destination: '%kernel.project_dir%/public/upload/images/domain'
        wine_profile_images:
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            uri_prefix: /upload/images/wine_profile
            upload_destination: '%kernel.project_dir%/public/upload/images/wine_profile'
        slider_home_images:
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            uri_prefix: /upload/images/slider_home
            upload_destination: '%kernel.project_dir%/public/upload/images/slider_home'
        slider_mpmd_images:
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            uri_prefix: /upload/images/mpmd
            upload_destination: '%kernel.project_dir%/public/upload/images/mpmd'
        slider_mpmd_file:
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            uri_prefix: /upload/files/mpmd
            upload_destination: '%kernel.project_dir%/public/upload/files/mpmd'
        dish_images:
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            uri_prefix: /upload/files/dish
            upload_destination: '%kernel.project_dir%/public/upload/files/dish'
        tastuce_theme_images:
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            uri_prefix: /upload/files/tastuce_theme
            upload_destination: '%kernel.project_dir%/public/upload/files/tastuce_theme'
        global_images:
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            uri_prefix: /upload/files/global
            upload_destination: '%kernel.project_dir%/public/upload/files/global'