version: "3.1"

services:
    # Core configuration
    php-fpm:
        container_name: ${CONTAINER_NAME}_php-fpm
        build: .
#        environment:
#            BLACKFIRE_SERVER_ID: '${BLACKFIRE_SERVER_ID}'
#            BLACKFIRE_SERVER_TOKEN: '${BLACKFIRE_SERVER_TOKEN}'
        ports:
            - '${PHP_PORT}:9000'
        volumes:
            - './:${WORKPATH}:rw'
        restart: always

    nginx:
        container_name: ${CONTAINER_NAME}_nginx
        image: nginx
        ports:
            - '${NGINX_PORT}:80'
        links:
            - php-fpm
        volumes:
            - './:${WORKPATH}:rw'
            - './docker/nginx/conf/core/core.conf:/etc/nginx/conf/nginx.conf:ro'
            - './docker/nginx/conf/development:/etc/nginx/conf.d:ro'
            # - './docker/nginx/conf/production:/etc/nginx/conf.d:ro' -> Uncomment this line for production.
            - './docker/nginx/logs/:/var/log/nginx'
        restart: always

    # Frontend configuration
    node:
        container_name: ${CONTAINER_NAME}_nodejs
        build: './docker/node'
        links:
            - php-fpm
        volumes:
            - './:${WORKPATH}:rw'
        working_dir: ${WORKPATH}



    # MariaDB Configuration
    mysql:
        container_name: ${CONTAINER_NAME}_mariadb
        image: mysql:5.7.28
        environment:
            MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MYSQL_USER: ${MARIADB_USER}
            MYSQL_PASSWORD: ${MARIADB_PASSWORD}
            MYSQL_DATABASE: ${MARIADB_NAME}
        ports:
            - '${MARIADB_PORT}:3306'
        volumes:
            - 'mysqlproject:/var/lib/mysql:rw'

#    # Performances configuration
#    blackfire:
#        container_name: ${CONTAINER_NAME}_blackfire
#        image: blackfire/blackfire
#        environment:
#            BLACKFIRE_SERVER_ID: '${BLACKFIRE_SERVER_ID}'
#            BLACKFIRE_SERVER_TOKEN: '${BLACKFIRE_SERVER_TOKEN}'
#            BLACKFIRE_CLIENT_ID: '${BLACKFIRE_CLIENT_ID}'
#            BLACKFIRE_CLIENT_TOKEN: '${BLACKFIRE_CLIENT_TOKEN}'
#        links:
#            - php-fpm
#        volumes:
#            - './:${WORKPATH}:rw'
#        restart: always

volumes:
    mysqlproject:
