easy_admin:
    entities:
        BoxWine:
            class: App\Entity\BoxWine
            templates:
                list: 'bundles/EasyAdminBundle/BoxWine/list.html.twig'
            list:
                title: 'Liste des boxs du moment'
                fields:
                    - property: createdAt
                      label: 'Crée le'
                    - property: isActive
                      label: 'Box active ?'
                      css_class: 'is-active'
                    - property: name
                      label: 'Nom'
                    - property: wines
                      label: 'Nombre de vins dans la box'
                    - property: price
                      label: 'Prix'
                    - property: 'imagePath'
                      label: 'Image de la box'
                      type: 'image'
                      base_path: '%app.path.box_images%'
            form:
                fields:
                    - property: isActive
                      label: 'Box active ?'
                    - { property: 'imageFile', type: 'vich_image', label: 'Photo box' }
                    - property: name
                      label: 'Nom de la box'
                      type: text
                    - property: shortPhrase
                      label: "Phrase d'accroche dans la box"
                      type: text
                    - property: description
                      label: "Description"
                      type: textarea
                    - property: wines
                      label: 'Vins contenus dans la box'
                    - property: price
                      label: 'Prix'

