easy_admin:
    entities:
        Delivery:
            class: App\Entity\Delivery
            disabled_actions: ["new", "delete"]
            list:
                title: 'Liste des livraisons'
                fields:
                    - property: order
                      label: 'Commande'
                    - property: status
                      label: 'Statut livraison'
                    - property: niche
                      label: "Date livraison à l'adresse"
                actions: ["show"]
