easy_admin:
    entities:
        NicheOfDelivery:
            disabled_actions: ['show']
            class: App\Entity\NicheOfDelivery
            list:
                title: "Liste des créneaux de livraison à l'adresse"
                sort: 'dateNiche'
                fields:
                    - property: dateNiche
                      label: 'Date du créneau'
                      format: 'd/m/Y'
                    - property: startAt
                      label: 'Heure début'
                      format: 'H:i'
                    - property: endAt
                      label: 'Heure fin'
                      format: 'H:i'
                    - property: numberNiche
                      label: 'Nombre de créneaux'
                      format: '%d'

            form:
                title: 'Nouveau créneau'
                fields:
                    - property: dateNiche
                      label: 'Date du créneau'
                      type: 'date'
                      type_options:
                          widget: 'single_text'
                          required: true
                    - property: startAt
                      label: 'Heure début créneau'
                      type: 'time'
                      type_options:
                          widget: 'single_text'
                          required: true
                    - property: endAt
                      label: 'Heure fin créneau'
                      type: 'time'
                      type_options:
                          widget: 'single_text'
                          required: true
                    - property: numberNiche
                      label: 'Nombre de créneaux disponible'
                      type: 'integer'
                      type_options:
                          required: true
