easy_admin:
    entities:
        NicheOfDelivery:
            disabled_actions: ['show']
            class: App\Entity\NicheOfDelivery
            list:
                title: "Liste des créneaux de livraison à l'adresse"
                fields:
                    - property: dateNiche
                      label: 'Date du créneau'
                      format: 'd/m/Y'
                    - property: numberNiche
                      label: 'Nombre de créneaux'
                      format: '%d'
                    - property: deliveries
                      label: 'Nombre de livraisons prévues sur ce créneau'

            new:
                title: 'Nouveau créneau'
                fields:
                    - property: dateNiche
                      label: 'Date du créneau'
                      type: 'date'
                      type_options:
                          widget: 'single_text'
                          required: false
                    - property: numberNiche
                      label: 'Nombre de créneaux disponible'
                      type: 'integer'
                      type_options:
                          required: false
#                    - property: address.streetName
#                      label: 'Nom de la rue'
#                      type: 'text'
#                      type_options:
#                          required: false
#                    - property: address.complement
#                      label: "Complément d'adresse"
#                      type: 'text'
#                      type_options:
#                          required: false
#                    - property: address.zipCode
#                      label: 'Code postal'
#                      type: 'text'
#                      type_options:
#                          required: false
#                    - property: address.city
#                      label: 'Ville'
#                      type: 'text'
#                      type_options:
#                          required: false
#                    - property: address.country
#                      label: 'Pays'
#                      type: 'country'
#                      type_options:
#                          required: false
