easy_admin:
    entities:
        Order:
            disabled_actions: ['new', 'edit', 'delete']
            templates:
                new: 'bundles/EasyAdminBundle/Order/new.html.twig'
                edit: 'bundles/EasyAdminBundle/Order/new.html.twig'
            class: App\Entity\Order
            search:
                - property: customer

            list:
                title: 'Liste des commandes'
                sort: ['orderAt', 'DESC']
                actions:
                    - name: show
                      icon: eye
                      label: ''
                    - name: edit_invoice
                      type: route
                      icon: invoice
                      label: 'Facture'
                fields:
                    - property: customer
                      label: 'Acheteur'
                      template: 'admin/fields/order/_customer.html.twig'
                    - property: orderNumber
                      label: 'N째 commande'
                    - property: billNumber
                      label: 'N째 Facture'
                    - property: status
                      label: 'Status'
                    - property: countBottle
                      label: 'Nbre de bouteilles'
                      template: 'admin/fields/order/_list_bottles.html.twig'
                    - property: countCubis
                      label: 'Nbre de cubis'
                      template: 'admin/fields/order/_list_cubis.html.twig'
                    - property: orderAt
                      label: 'Date commande'
            show:
                fields:
                    - property: customer
                      label: 'Acheteur'
                    - property: billNumber
                      label: 'N째 facture'
                    - property: orderNumber
                      label: 'N째 commande'
                    - property: orderAt
                      label: 'Date commande'
                    - property: customerStripeId
                      label: 'Identifiant acheteur Stripe'
                    - property: lines
                      label: 'Ligne de produit'
                    - property: delivery
                      label: 'Livraison'
                    - property: getTotalAmount
                      label: 'Montant de la commande'
