easy_admin:
    entities:
        Order:
            templates:
                new: 'bundles/EasyAdminBundle/Order/new.html.twig'
                edit: 'bundles/EasyAdminBundle/Order/new.html.twig'
            class: App\Entity\Order
            list:
                title: 'Liste des commandes'
                sort: ['orderAt', 'DESC']
                fields:
                    - property: orderNumber
                      label: 'N° commande'
                    - property: billNumber
                      label: 'N° Facture'
                    - property: countAmountOrder
                      label: 'Montant commande'
                    - property: status
                      label: 'Status'
                    - property: lines
                      label: 'Nbre de produits'
                    - property: countProducts
                      label: 'Nbre de bouteilles'
                    - property: orderAt
                      label: 'Date commande'
            new:
                fields:
                    - type: 'group'
                      label: 'Produits'
                      columns: 6
                    - property: lines
                      label: false
                      type: 'collection'
                      type_options:
                          entry_type: App\Admin\Forms\AddOrderLineType
                          allow_delete: true
                          allow_add: true
                          by_reference: false
                      columns: 12
                    - type: 'group'
                      label: 'Livraison'
                      columns: 6
                    - property: delivery.status
                      label: 'Status'
                      type: choice
                      type_options:
                          choices: {'Livraison en cours': 'Livraison en cours', 'Livré en point relais': 'Livré en point relais', "Livré à l'adresse": "Livré à l'adresse"}
                    - property: delivery.deliveryType
                      label: 'Type de livraison'
                      type: entity
                      type_options:
                          class: App\Entity\DeliveryType
                    - property: delivery.deliveryPoint
                      type: entity
                      label: 'Point relais'
                      attr:
                          class: 'delivery-point hidden'
                      type_options:
                          class: App\Entity\DeliveryPoint
                    - property: delivery.niche
                      type: entity
                      label: 'Créneau de livraison'
                      css_class: 'niche-delivery hidden'
                      type_options:
                          class: App\Entity\NicheOfDelivery
                          query_builder: 'App\Repository\NicheOfDeliveryRepository::listFreeNiche'
            edit:
                title: Modification %%entity_label%%
                fields:
                    -   type: 'group'
                        label: 'Produits'
                        columns: 6
                    -   property: lines
                        label: false
                        type: 'collection'
                        type_options:
                            entry_type: App\Admin\Forms\AddOrderLineType
                            allow_delete: true
                            allow_add: true
                            by_reference: false
                        columns: 12
                    -   type: 'group'
                        label: 'Livraison'
                        columns: 6
                    -   property: delivery.status
                        label: 'Status'
                        type: choice
                        type_options:
                            choices: {'Livraison en cours': 'Livraison en cours', 'Livré en point relais': 'Livré en point relais', "Livré à l'adresse": "Livré à l'adresse"}
                    -   property: delivery.deliveryType
                        label: 'Type de livraison'
                        type: entity
                        type_options:
                            class: App\Entity\DeliveryType
                    -   property: delivery.deliveryPoint
                        type: entity
                        label: 'Point relais'
                        attr:
                            class: 'delivery-point hidden'
                        type_options:
                            class: App\Entity\DeliveryPoint
                    -   property: delivery.niche
                        type: entity
                        label: 'Créneau de livraison'
                        css_class: 'niche-delivery hidden'
                        type_options:
                            class: App\Entity\NicheOfDelivery
                            query_builder: 'App\Repository\NicheOfDeliveryRepository::listFreeNiche'
