easy_admin:
    entities:
        Product:
            class: App\Entity\Product
            templates:
                edit: 'bundles/EasyAdminBundle/Product/edit.html.twig'
            list:
                form_filters:
                    - property: active
                      label: 'Produit actif'
                    - property: typeProduct
                      label: 'Type'
                    - property: domain
                      label: 'Domaine'
                    - property: profile
                      label: 'Profil'
                title: 'Liste des produits'
                fields:
                    - property: active
                      label: 'Actif ?'
                    - property: isPromote
                      label: 'Mis en avant'
                    - property: profile
                      label: 'Profil'
                    - property: domain
                      label: 'Domaine'
                    - property: vintageName
                      label: 'Nom de la cuvée'
                    - property: appellation
                      label: 'Appellation'
                    - property: year
                      label: 'Année'
                    - property: typeProduct
                      label: 'Type de vin'
                    -   property: 'imagePath'
                        type: 'image'
                        base_path: '%app.path.product_images%'
            form:
                fields:
                    - type: 'group'
                      label: 'Informations générales'
                      columns: 12
                    - { property: 'imageFile', type: 'vich_image', label: 'Photo produit', columns: 4 }
                    - { property: 'firstBadgeFile', type: 'vich_image', label: '1er Badge', columns: 4 }
                    - { property: 'secondBadgeFile', type: 'vich_image', label: '2ème badge', columns: 4 }
                    - property: region
                      label: 'Région'
                      type: 'choice'
                      type_options:
                          choices:
                              Alsace: Alsace
                              Beaujolais: Beaujolais
                              Bordeaux: Bordeaux
                              Bourgogne: Bourgogne
                              Champagne: Champagne
                              Languedoc: Languedoc
                              Provence: Provence
                              Roussilon: Roussilon
                              Savoie: Savoie
                              Sud-ouest: Sud-ouest
                              Val de loire: Val de loire
                              Vallée du Rhône: Vallée du Rhône
                      columns: 4
                    - property: domain
                      label: 'Domaine'
                      type: 'easyadmin_autocomplete'
                      columns: 4
                    - property: vintageName
                      label: 'Nom de la cuvée'
                      type: 'text'
                      columns: 4
                    - property: year
                      type: 'text'
                      label: 'Année'
                      columns: 4
                    - property: appellation
                      type: 'text'
                      label: 'Appellation'
                      columns: 4
                    - property: shortPhrase
                      type: 'text'
                      label: 'Description courte'
                      columns: 4
                    - property: alcoholDegree
                      type: 'text'
                      label: "Degré d'alcool"
                      columns: 4
                    - { property: 'typeProduct', label: 'Type de vin', type: 'easyadmin_autocomplete', type_options: { attr: { create: true } }, columns: 4 }
                    - property: profile
                      type: 'easyadmin_autocomplete'
                      type_options:
                          attr:
                              create: true
                      label: 'Profil'
                      columns: 4
                    - property: tvaRate
                      type: number
                      label: '% TVA'
                      columns: 4
                    - type: 'group'
                      label: 'Informations vin'
                      columns: 4
                    - property: wineCaract.fruity
                      type: 'choice'
                      type_options:
                          choices:
                              20: 20
                              40: 40
                              60: 60
                              80: 80
                              100: 100
                      label: 'Fruité'
                    - property: wineCaract.taste
                      type: 'choice'
                      label: 'Saveur'
                      type_options:
                          choices: {'Tannique': 'Tannique', 'Onctueux': 'Onctueux', "Frais": "Frais", "Corsé": "Corsé"}
                    - property: wineCaract.robustness
                      type: 'choice'
                      type_options:
                          choices:
                              20: 20
                              40: 40
                              60: 60
                              80: 80
                              100: 100
                      label: 'Corps'
                    - type: 'group'
                      label: 'Service'
                      columns: 4
                    - property: wineService.temp
                      type: 'integer'
                      label: 'Température de service'
                    - property: wineService.decanting
                      label: 'Carafage'
                    - property: wineService.opportunity
                      label: 'Occasion'
                      type: 'text'
                    - property: wineService.grape
                      type: 'collection'
                      type_options:
                          entry_type: 'Symfony\Component\Form\Extension\Core\Type\TextType'
                          allow_add: true
                          allow_delete: true
                          prototype: true
                          prototype_data: 'Nouveau cépage'
                      label: 'Cépage'
                    - property: agreements
                      label: 'Les accords'
                      type: entity
                      type_options:
                          class: App\Entity\WineAgreement
                          multiple: true
                          query_builder: 'App\Repository\WineAgreementRepository::getOrderAgreement'
                    - property: dishes
                      label: 'Les mets'
                      type: collection
                      type_options:
                          entry_type: 'App\Admin\Forms\DishType'
                          allow_add: true
                          allow_delete: true
                          prototype: true
                          by_reference: false

