easy_admin:
    entities:
        Product:
            class: App\Entity\Product
            templates:
                edit: 'bundles/EasyAdminBundle/Product/edit.html.twig'
            list:
                form_filters:
                    - property: active
                      label: 'Produit actif'
                    - property: typeProduct
                      label: 'Type'
                    - property: domain
                      label: 'Domaine'
                    - property: profile
                      label: 'Profil'
                title: 'Liste des produits'
                fields:
                    - property: active
                      label: 'Actif ?'
                    - property: isPromote
                      label: 'Mis en avant'
                    - property: profile
                      label: 'Profil'
                    - property: domain
                      label: 'Domaine'
                    - property: vintageName
                      label: 'Nom de la cuvée'
                    - property: appellation
                      label: 'Appellation'
                    - property: year
                      label: 'Année'
                    - property: typeProduct
                      label: 'Type de vin'
                    -   property: 'imagePath'
                        type: 'image'
                        base_path: '%app.path.product_images%'
            form:
                fields:
                    - type: 'group'
                      label: 'Informations générales'
                      columns: 4
                    - { property: 'imageFile', type: 'vich_image', label: 'Photo produit' }
                    - { property: 'firstBadgeFile', type: 'vich_image', label: '1er Badge' }
                    - { property: 'secondBadgeFile', type: 'vich_image', label: '2ème badge' }
                    - property: domain
                      label: 'Domaine'
                      type: 'easyadmin_autocomplete'
                    - property: vintageName
                      label: 'Nom de la cuvée'
                      type: 'text'
                    - property: year
                      type: 'text'
                      label: 'Année'
                    - property: appellation
                      type: 'text'
                      label: 'Appellation'
                    - property: shortPhrase
                      type: 'text'
                      label: 'Description courte'
                    - property: alcoholDegree
                      type: 'text'
                      label: "Degré d'alcool"
                    - { property: 'typeProduct', label: 'Type de vin', type: 'easyadmin_autocomplete', type_options: { attr: { create: true } } }
                    - property: profile
                      type: 'easyadmin_autocomplete'
                      type_options:
                          attr:
                              create: true
                      label: 'Profil'
                    - property: tvaRate
                      type: number
                      label: '% TVA'
                    - type: 'group'
                      label: 'Informations vin'
                      columns: 4
                    - property: wineCaract.fruity
                      type: 'integer'
                      label: 'Fruité'
                    - property: wineCaract.taste
                      type: 'choice'
                      label: 'Goût'
                      type_options:
                          choices: {'Tannique': 'Tannique', 'Onctueux': 'Onctueux', "Frais": "Frais"}
                    - property: wineCaract.robustness
                      type: 'choice'
                      label: 'Robustesse'
                      type_options:
                          choices: {'Mince': 'Mince', 'Charnu': 'Charnu', "Musclé": "Musclé"}
                    - type: 'group'
                      label: 'Service'
                      columns: 4
                    - property: wineService.temp
                      type: 'integer'
                      label: 'Température de service'
                    - property: wineService.decanting
                      label: 'Carafage'
                    - property: wineService.opportunity
                      label: 'Occasion'
                      type: 'text'
                    - property: wineService.grape
                      type: 'collection'
                      type_options:
                          entry_type: 'Symfony\Component\Form\Extension\Core\Type\TextType'
                          allow_add: true
                          allow_delete: true
                          prototype: true
                          prototype_data: 'Nouveau cépage'
                      label: 'Cépage'
                    - type: 'group'
                      label: 'Contenance'
                      columns: 12
                    - property: capacities
                      label: ''
                      type: embedded_list
                    - type: 'group'
                      label: 'Promotions'
                      columns: 12
                    - property: promotions
                      label: ''
                      type: embedded_list
                      type_options:
                        entity: Promotion
                        filters:
                            'entity.promotions': 'form:parent.data.id'
