easy_admin:
    entities:
        Product:
            class: App\Entity\Product
            list:
                form_filters:
                    - property: typeProduct
                      label: 'Type'
                    - property: domain
                      label: 'Domaine'
                    - property: profile
                      label: 'Profil'
                title: 'Liste des produits'
                fields:
                    - property: domain
                      label: 'Domaine'
                    - property: vintageName
                      label: 'Nom de la cuvée'
                    - property: appellation
                      label: 'Appellation'
                    - property: year
                      label: 'Année'
                    - property: typeProduct
                      label: 'Type de vin'
                    - property: profile
                      label: 'Profil'
                    - property: price
                      label: 'Prix unitaire'

            form:
                fields:
                    - type: 'tab'
                      label: 'Informations générales'
                    - property: domain
                      label: 'Domaine'
                      type: 'easyadmin_autocomplete'
                      type_options:
                          attr:
                              create: true
                    - property: vintageName
                      label: 'Nom de la cuvée'
                      type: 'text'
                    - property: year
                      type: 'text'
                      label: 'Année'
                    - property: appellation
                      type: 'text'
                      label: 'Appellation'
                    - { property: 'typeProduct', type: 'easyadmin_autocomplete', type_options: { attr: { create: true } } }
                    - property: profile
                      type: 'easyadmin_autocomplete'
                      type_options:
                          attr:
                              create: true
                    - property: price
                      type: number
                      label: 'Prix unitaire'
                    - type: 'tab'
                      label: 'Informations vin'
                    - property: wineCaract.powerful
                      type: 'integer'
                      label: 'Puissant'
                    - property: wineCaract.complex
                      type: 'integer'
                      label: 'Complexe'
                    - property: wineCaract.spice
                      type: 'integer'
                      label: 'Epicé'
                    - property: wineCaract.fruity
                      type: 'integer'
                      label: 'Fruité'
                    - property: wineCaract.wooded
                      type: 'integer'
                      label: 'Boisé'
                    - property: wineCaract.tannic
                      type: 'integer'
                      label: 'Tannique'
                    - type: 'tab'
                      label: 'Service'
                    - property: wineService.temp
                      type: 'integer'
                      label: 'Température de service'

                    - property: wineService.decanting
                      type: 'text'
                      label: 'Carafage'
                    - property: wineService.meat
                      type: 'textarea'
                      label: 'Viandes associés'
                      attr:
                          rows: 1
                    - property: wineService.cheese
                      type: 'textarea'
                      label: 'Fromages associés'
                    - property: wineService.fish
                      type: 'textarea'
                      label: 'Poissons associés'
                    - property: wineService.vegetable
                      type: 'textarea'
                      label: 'Légumes associés'
                    - property: wineService.dessert
                      type: 'textarea'
                      label: 'Desserts associés'

