easy_admin:
    entities:
        Promotion:
            class: App\Entity\Promotion
            list:
                form_filters:
                    - property: product
                      label: 'Vins'
                    - property: typePromotion
                      label: 'Type de promotion'
                sort: ['startAt', 'DESC']
                max_results: 20
                title: 'Liste des promotions'
                fields:
                    - property: product
                      label: 'Produit'
                      template: 'admin/fields/promotions/_product.html.twig'
                    - property: typePromotion
                      label: 'Type promotion'
                    - property: value
                      label: 'Valeur'
                    - property: status
                      label: 'Statut'
                    - property: startAt
                      label: 'Débute le'
                      format: 'd/m/Y'
                    - property: endAt
                      label: 'Termine le'
                      format: 'd/m/Y'

            form:
                fields:
                    - property: name
                      type: 'text'
                      label: 'Nom de la promotion'
                    - property: product
                      type: 'entity'
                      label: 'Vin'
                      type_options:
                          class: 'App\Entity\Product'
                    - property: typePromotion
                      type: 'entity'
                      type_options:
                          class: 'App\Entity\TypePromotion'
                      label: 'Type de promotion'
                    - property: value
                      type: number
                      label: 'Valeur'
                    - property: startAt
                      type: date
                      label: 'Date de début'
                    - property: endAt
                      type: date
                      label: 'Date de fin'
