easy_admin:
    entities:
        Promotion:
            class: App\Entity\Promotion
            list:
                title: 'Liste des catégories de vins'
                fields:
                    - property: product
                      label: 'Produit'
                    - property: typePromotion
                      label: 'Type promotion'
                    - property: value
                      label: 'Valeur'
                    - property: status
                      label: 'Statut'
                    - property: countOrderWithPromotion
                      label: 'Commandes'
                    - property: startAt
                      label: 'Débute le'
                    - property: endAt
                      label: 'Termine le'

            form:
                fields:
                    - property: name
                      type: 'text'
                      label: 'Nom de la promotion'
                    - property: product
                      type: 'easyadmin_autocomplete'
                      label: 'Vin'
                    - property: typePromotion
                      type: 'entity'
                      type_options:
                          class: 'App\Entity\TypePromotion'
                      label: 'Type de promotion'
                    - property: value
                      type: number
                      label: 'Valeur'
                    - property: startAt
                      type: date
                      label: 'Date de début'
                    - property: endAt
                      type: date
                      label: 'Date de fin'
