easy_admin:
    entities:
        SliderMPMD:
            class: App\Entity\SliderMPMD
            list:
                title: 'Liste des slides'
                fields:
                    - property: image
                      type: 'image'
                      base_path: '%app.path.slider_mpmd_images%'
                    - property: pdf
                      type: 'file'
                      base_path: '%app.path.slider_mpmd_file%'
            form:
                fields:
                    - property: 'imageFile'
                      type: 'vich_image'
                      label: 'Image'
                      required: true
                    - property: pdfFile
                      type: 'vich_file'
                      label: 'Fichier PDF'
                      required: true
