easy_admin:
    entities:
        SliderMPMDDaygust:
            class: App\Entity\SliderMPMD
            list:
                title: 'Liste des slides'
                fields:
                    - property: type
                      label: 'MPMD / Daygust'
                    - property: image
                      type: 'image'
                      base_path: '%app.path.slider_mpmd_images%'
                    - property: pdf
                      type: 'file'
                      base_path: '%app.path.slider_mpmd_file%'
            form:
                fields:
                    - property: type
                      type: choice
                      type_options:
                          choices: {'Ma Première Méthode de Dégustation': 'mpmd', 'Daygust': 'daygust'}
                    - property: 'imageFile'
                      type: 'vich_image'
                      label: 'Image'
                      required: true
                    - property: pdfFile
                      type: 'vich_file'
                      label: 'Fichier PDF'
                      required: true
                    - property: textContent
                      type: 'fos_ckeditor'
                      label: 'Contenu textuel du slider'
