easy_admin:
    entities:
        Stock:
            templates:
                edit: 'bundles/EasyAdminBundle/Stock/edit.html.twig'
            class: App\Entity\Stock
            disabled_actions: ['new', 'delete']
            list:
                title: 'Liste des stocks produits'
                form_filters:
                    - { name: lowerThan, property: quantity, label: 'Stock <', operator: lt }
                    - { name: greaterOrEqualThan, property: quantity, label: 'Stock >=', operator: gte }
                fields:
                    - property: capacity.wine
                      label: 'Vin'
                    - property: capacity.getCapacityFullname
                      label: 'Contenance'
                    - property: capacity.getTotalQuantity
                      label: 'Quantité restante'
                      format: '%d'
                    - property: updatedAt
                      label: 'Date de mise à jour'
            form:
                fields:
                    - property: stockEntries
                      label: false
                      type: 'collection'
                      css_class: 'col-12'
                      type_options:
                          entry_type: App\Admin\Forms\AddStockEntryType
                          allow_delete: true
                          allow_add: true
                          by_reference: false

