easy_admin:
    entities:
        StockEntry:
            templates:
                edit: 'bundles/EasyAdminBundle/Stock/edit.html.twig'
            class: App\Entity\Stock
            disabled_actions: ['edit']
            list:
#                title: 'Liste des stocks produits'
                fields:
                    - property: wine
                      label: 'Vin'
                    - property: quantity
                      label: 'Quantité sur le mouvement'
                      type: integer
                    - property: createdAt
                      label: 'Mouvement réalisé le'
