easy_admin:
    entities:
        Stock:
            templates:
                edit: 'bundles/EasyAdminBundle/Stock/edit.html.twig'
            class: App\Entity\Stock
            disabled_actions: ['new', 'delete']
            list:
                title: 'Liste des stocks produits'
                form_filters:
                    - { name: lowerThan, property: quantity, label: 'Stock <', operator: lt }
                    - { name: greaterOrEqualThan, property: quantity, label: 'Stock >=', operator: gte }
                    - { name: like, property: capacity, label: 'Vin', operator: like}

                fields:
                    - property: capacity.wine
                      label: 'Vin'
                      template: 'admin/fields/capacity/_wine.html.twig'
                    - property: capacity.getCapacityFullname
                      label: 'Contenance'
                    - property: quantity
                      label: 'Quantité restante'
                      format: '%d'
                    - property: updatedAt
                      label: 'Date de mise à jour'
                    - property: countTotalBottlesSold
                      label: "Nombres vendus"
            form:
                fields:
                    - property: quantity
                      label: 'Quantité restante'
                      help: 'Il vous ai possible de modifier le stock existant.'
                    - property: stockEntries
                      label: Liste des mouvements de stock pour cette contenance
                      type: 'collection'
                      css_class: 'col-12'
                      type_options:
                          entry_type: App\Admin\Forms\AddStockEntryType
                          allow_delete: true
                          allow_add: true
                          by_reference: false

