easy_admin:
    entities:
        StockEntry:
            templates:
                edit: 'bundles/EasyAdminBundle/Stock/edit.html.twig'
            class: App\Entity\StockEntry
            disabled_actions: ['edit', 'new', 'delete']
            list:
                form_filters:
                    - { property: typeEntry, label: 'Type de mouvement', type_options: { choices: { Entrée: entree, Sortie: sortie } } }
                title: 'Liste des mouvements de stock'
                sort: ['createdAt', 'DESC']
                fields:
                    - property: typeEntry
                      label: 'Entrée / Sortie'
                    - property: quantity
                      label: 'Quantité sur le mouvement'
                      type: integer
                    - property: createdAt
                      label: 'Mouvement réalisé le'
                    - property: getTypeWine
                      label: 'Type de vin'
                    - property: getWineName
                      label: 'Nom du vin'
                    - property: getCapacityName
                      label: 'Contenance'
                    - property: order
                      label: 'Commande associée'
