easy_admin:
    entities:
        VineProfile:
            class: App\Entity\VineProfile
            templates:
                list: 'bundles/EasyAdminBundle/VineProfile/list.html.twig'
            list:
                title: 'Liste des profils de vins'
                sort: order
                fields:
                    - property: order
                      label: "Ordre d'affichage"
                      format: '%d'
                    - property: type
                      label: "Type de profil"
                    - property: name
                      label: 'Nom'
                    - property: description
                      label: 'Résumé'
                    - property: color
                      label: 'Couleur du profil'
                    - property: colorText
                      label: 'Couleur du texte'
                    - property: 'imagePath'
                      type: 'image'
                      base_path: '%app.path.wine_profile_images%'
                      label: 'Icône du profil'
            new:
                fields:
                    - { property: 'imageFile', type: 'vich_image', label: 'Icône profil' }
                    - property: type
                      label: 'Type de profil'
                      type: 'choice'
                      type_options:
                        choices: {'Les rouges': 'Les rouges', 'Les rosés': 'Les rosés', "Les blancs": "Les blancs"}
                    - property: order
                      type: integer
                      label: "Ordre d'affichage dans le type"
                    - property: 'name'
                      type: 'text'
                      label: 'Nom'
                    - property: description
                      type: 'text'
                      label: 'Résumé'
                    - property: longDescription
                      type: textarea
                      label: 'Description'
                    - property: 'color'
                      type: 'color'
                      label: 'Couleur du profil'
                      type_options:
                          data: '#ffffff'
                    - property: 'colorText'
                      type: 'color'
                      label: 'Couleur du texte'
                      type_options:
                        data: '#000000'
            edit:
                fields:
                    - { property: 'imageFile', type: 'vich_image', label: 'Icône profil' }
                    -   property: order
                        type: integer
                        label: "Ordre d'affichage dans le type"
                    - property: type
                      label: 'Type de profil'
                      type: 'choice'
                      type_options:
                        choices: {'Les rouges': 'Les rouges', 'Les rosés': 'Les rosés', "Les blancs": "Les blancs"}
                    - property: 'name'
                      type: 'text'
                      label: 'Nom'
                    - property: description
                      type: 'text'
                      label: 'Résumé'
                    - property: longDescription
                      type: textarea
                      label: 'Description'
                    - property: 'color'
                      type: 'color'
                      label: 'Couleur du profil'
                    - property: 'colorText'
                      type: 'color'
                      label: 'Couleur du texte'
                      type_options:
                        data: '#000000'

