easy_admin:
    entities:
        VineProfile:
            class: App\Entity\VineProfile
            templates:
                list: 'bundles/EasyAdminBundle/VineProfile/list.html.twig'
            list:
                title: 'Liste des profils de vins'
                fields:
                    - property: name
                      label: 'Nom'
                    - property: color
                      label: 'Couleur du profil'
            new:
                fields:
                    - property: 'name'
                      type: 'text'
                      label: 'Nom'
                    - property: 'color'
                      type: 'color'
                      label: 'Couleur du profil'
                      type_options:
                          data: '#ffffff'
            edit:
                fields:
                    - property: 'name'
                      type: 'text'
                      label: 'Nom'
                    - property: 'color'
                      type: 'color'
                      label: 'Couleur du profil'

