# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.path.product_images: /upload/images/products
    app.path.domain_images: /upload/images/domain
    app.path.wine_profile_images: /upload/images/wine_profile
    app.path.slider_home_images: /upload/images/slider_home
    app.path.tastuce_theme_images: /upload/images/tastuce_theme
    app.path.slider_mpmd_images: /upload/images/mpmd
    app.path.slider_mpmd_file: /upload/files/mpmd
    app.path.dish_images: /upload/files/dish
    app.path.global_images: /upload/files/global
    app.path.breadcrumb_images: /upload/files/breadcrumb
    app.path.box_images: /upload/files/box

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $apiPrivateKeyStripe: '%env(resolve:API_PRIVATE_STRIPE)%'
            $dsn: '%env(resolve:MAILER_DSN)%'
            $publicPath: '%kernel.project_dir%/public'
            $tmpBillFolder: '%kernel.project_dir%/var/bill/'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,DoctrineMigrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Actions\:
        resource: '../src/Actions'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
